/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ismt.bank;

/**
 *
 * @author bikes
 */
public class BankApp extends javax.swing.JFrame {
    BankControllerInterface bc;
    /**
     * Creates new form BankApp
     */
    public BankApp() {
        initComponents();
        bc = new BankControllerMYSQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        exitMenu = new javax.swing.JMenu();
        jExitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        newAccountMenu = new javax.swing.JMenuItem();
        deleteAccountMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        allAccountsViewMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        withdrawMenu = new javax.swing.JMenuItem();
        depositMenu = new javax.swing.JMenuItem();
        fundTransferMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CORE BANKING SYSTEM");

        exitMenu.setText("File");

        jExitMenu.setText("Exit");
        jExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitMenuActionPerformed(evt);
            }
        });
        exitMenu.add(jExitMenu);

        jMenuBar1.add(exitMenu);

        jMenu2.setText("Account");

        newAccountMenu.setText("New Account");
        newAccountMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountMenuActionPerformed(evt);
            }
        });
        jMenu2.add(newAccountMenu);

        deleteAccountMenu.setText("Delete Account");
        deleteAccountMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountMenuActionPerformed(evt);
            }
        });
        jMenu2.add(deleteAccountMenu);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("View");

        allAccountsViewMenu.setText("All Accounts");
        allAccountsViewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allAccountsViewMenuActionPerformed(evt);
            }
        });
        jMenu1.add(allAccountsViewMenu);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Transaction");

        withdrawMenu.setText("Withdraw");
        withdrawMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawMenuActionPerformed(evt);
            }
        });
        jMenu3.add(withdrawMenu);

        depositMenu.setText("Deposit");
        depositMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositMenuActionPerformed(evt);
            }
        });
        jMenu3.add(depositMenu);

        fundTransferMenu.setText("Fund Transfer");
        fundTransferMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundTransferMenuActionPerformed(evt);
            }
        });
        jMenu3.add(fundTransferMenu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newAccountMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountMenuActionPerformed
        // TODO add your handling code here:
        NewAccountWindow naw = new NewAccountWindow(bc);
        this.add(naw);
        naw.setVisible(true);
    }//GEN-LAST:event_newAccountMenuActionPerformed

    private void jExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jExitMenuActionPerformed

    private void deleteAccountMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountMenuActionPerformed
        // TODO add your handling code here:
        DeleteAccountWindow daw = new DeleteAccountWindow(bc);
        this.add(daw);
        daw.setVisible(true);
    }//GEN-LAST:event_deleteAccountMenuActionPerformed

    private void depositMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositMenuActionPerformed
        // TODO add your handling code here:
        DepositWindow dw = new DepositWindow(bc);
        this.add(dw);
        dw.setVisible(true);
    }//GEN-LAST:event_depositMenuActionPerformed

    private void allAccountsViewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allAccountsViewMenuActionPerformed
        // TODO add your handling code here:
        ListAllAccounts laa = new ListAllAccounts(bc);
        this.add(laa);
        laa.setVisible(true);    
    }//GEN-LAST:event_allAccountsViewMenuActionPerformed

    private void withdrawMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawMenuActionPerformed
        // TODO add your handling code here:
        WithdrawAccountWindow waw = new WithdrawAccountWindow(bc);
        this.add(waw);
        waw.setVisible(true);
    }//GEN-LAST:event_withdrawMenuActionPerformed

    private void fundTransferMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundTransferMenuActionPerformed
        // TODO add your handling code here:
        FundTransferWindow ftw = new FundTransferWindow();
        this.add(ftw);
        ftw.setVisible(true);
    }//GEN-LAST:event_fundTransferMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem allAccountsViewMenu;
    private javax.swing.JMenuItem deleteAccountMenu;
    private javax.swing.JMenuItem depositMenu;
    private javax.swing.JMenu exitMenu;
    private javax.swing.JMenuItem fundTransferMenu;
    private javax.swing.JMenuItem jExitMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem newAccountMenu;
    private javax.swing.JMenuItem withdrawMenu;
    // End of variables declaration//GEN-END:variables
}
